<a href="https://colab.research.google.com/github/Puzziii/LegalEase/blob/main/Movie_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as mp
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [66]:
df = pd.read_csv('movies_metadata.csv', encoding='ISO-8859-1', on_bad_lines='skip', engine='python')

In [67]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [68]:
df.shape

(45271, 24)

In [69]:
df.isnull().sum()

adult                       14
belongs_to_collection    40749
budget                       5
genres                       5
homepage                 37466
id                           5
imdb_id                     22
original_language           16
original_title              21
overview                  1060
popularity                 115
poster_path                574
production_companies       120
production_countries       114
release_date               197
revenue                    116
runtime                    461
spoken_languages           212
status                     293
tagline                  24980
title                      213
video                      213
vote_average               213
vote_count                 213
dtype: int64

In [70]:
df.duplicated().sum()

np.int64(16)

In [71]:
df = df.drop_duplicates().reset_index(drop = True)

In [72]:
df.duplicated().sum()

np.int64(0)

In [73]:
df = df[['title', 'overview', 'genres', 'tagline', 'vote_average', 'popularity']]

In [74]:
df.shape

(45255, 6)

In [75]:
df.isnull().sum()

title             213
overview         1060
genres              5
tagline         24969
vote_average      213
popularity        115
dtype: int64

In [76]:
df = df.dropna(subset=['title'])

In [77]:
df.isnull().sum()

title               0
overview          951
genres              0
tagline         24756
vote_average        0
popularity          0
dtype: int64

In [78]:
df['overview'] = df['overview'].fillna('')

In [79]:
df.isnull().sum()

title               0
overview            0
genres              0
tagline         24756
vote_average        0
popularity          0
dtype: int64

In [80]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [81]:
import ast
df['genres'] = df['genres'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]))

In [82]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [83]:
df['tagline'] = df['tagline'].fillna('')

In [84]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [85]:
df['tags'] = df['overview'] + ' ' + df['genres'] + ' ' + df['tagline']

In [86]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [87]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [88]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [89]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [90]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [91]:
def preprocess_text(text):
  text = str(text).lower() # convert to lowercase
  text = re.sub(r'[^\w\s]', '', text) # Remove punctuations using regex
  words = text.split() # Split each words
  words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words] # remove stop words and tokenise each word
  return " ".join(words)

In [92]:
df['tags'] = df['tags'].apply(preprocess_text)
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [93]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [94]:
indices = pd.Series(df.index, index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45250
Century of Birthing            45251
Betrayal                       45252
Satan Triumphant               45253
Queerama                       45254
Length: 45042, dtype: int64

In [95]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [96]:
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1, 2), stop_words='english')

In [97]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [98]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1540866 stored elements and shape (45042, 50000)>

In [99]:
from sklearn.metrics.pairwise import cosine_similarity

In [100]:
def recommend(title, n = 10): # n = 10 is 10 movie reccomendation
  if title not in indices:
    return ['Movie Not Found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1] # Get Top 10 recomendation
  return df['title'].iloc[similar_idx]

In [101]:
recommend('Avatar')

34708                         Criminal Activities
18265                                   Cloportes
29978                              Poliisin poika
28051                                   Wild Card
2264     Police Academy 5: Assignment Miami Beach
8596                                    Tony Rome
11605                                   Wise Guys
41520                 My Family and Other Animals
11560                            Reno 911!: Miami
17846                                Tony Arzenta
Name: title, dtype: object

In [102]:
import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf, open('tfidf.pkl', 'wb'))

In [103]:
!git config --global user.email "poojithag102@gmail.com"
!git config --global user.name "Puzziii"

In [104]:
!git init
!git add .
!git commit -m "Initial commit - IMDB movie analysis"

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
[master (root-commit) 1d63975] Initial commit - IMDB movie analysis
 26 files changed, 96663 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2026.05.12/13.28.53.384927.log
 create mode 100644 .config/logs/2026.05.12/13.29.12.483949.log
 create mode 100644 .config/logs/2026.05.12/13.29.25.418951.log
 create mode 100644 .config/logs/2026.05.12/13.29.27.205677.log
 create mode 100644 .config/logs/2026.05.12/13.29.39.608616.log
 create mode 100644 .config/logs/2026.05.12/13.29.40.400999.log
 create mode 100644 df.pkl
 create mode 100644 indices.pkl
 create mode 100644 movies_metadata.csv
 create mode 100755 sample_data/README.md
 create mode 100755 sample_data/anscombe.json
 create mode 100644 sample_data/california_housing_test.csv
 create mode 100644 sample_data/california_housing_train.csv
 create mode 100644 sample_data/mnist_test.csv
 create mode 100644 sample_data/mnist_train_small.csv
 create mode 100644 tfidf.pkl
 create mode 100644 tfidf_matrix.pkl